### ISSUE TITLE
Videos Returning 403 When Running on Heroku 

### ISSUE THREAD

**Issue by c1d3rdev** [pionxzh/Pornhub.js#1]
Hey, thanks for this package!

I have an API using this package running locally which works great. When I push it to heroku and request a video, the video files return 403 for some reason...

Any idea as to why this might be happening?

**Comment by onupirat** [comment]
hey. Can you help a newbie? How to make this work locally as you do? I'm no programmer and am confused.

**Comment by Scraayp** [comment]
@c1d3rdev Because on heroku they are using a other root. That doesn' t meet the requirements probaly in your code.
