### ISSUE TITLE
Is there an option for random videos from pornhub

### ISSUE THREAD

**Issue by bobwatcherx** [pionxzh/Pornhub.js#108]
Suppose I have a website and on my home page it contains random videos from the tag or pornstar . Is there an example of the code? 

https://github.com/pionxzh/pornhub.js/blob/HEAD/doc/WebMaster.md#search-video

**Comment by pionxzh** [comment]
You can try these APIs:
- [get-recommended-videos](https://github.com/pionxzh/Pornhub.js/blob/master/doc/Page.md#get-recommended-videos)
  - This sounds like what you are looking for
- [get-random-video](https://github.com/pionxzh/Pornhub.js/blob/master/doc/Page.md#get-random-video)
  - This will give you **one** random video. 

You can also use `.pornstarList` to get pornstars and use `.modelVideos` to get their video list. I would suggest you storing them in a DB or Redis to reduce the query number.

`.autoComplete` is also a useful API for you to show some recommendations based on keywords or topics.
