### ISSUE TITLE
How to use this package without vpn

### ISSUE THREAD

**Issue by bobwatcherx** [pionxzh/Pornhub.js#109]
Because pornhub site Block in my country. Indonesia . And I can't embed pornhub videos. I have tried with node-unblocker to embed video but it is not working. is there a way to overcome that

**Comment by pionxzh** [comment]
1. For this package, you can check https://github.com/pionxzh/Pornhub.js/blob/master/doc/DOCUMENT.md#custom-agent-proxy section to see how to use VPN or proxy.
2. For video playing, it might be out of the scope of this package.
