### ISSUE TITLE
How come only models and not pornstars has a `mostRecentVideos` property?

### ISSUE THREAD

**Issue by iced-queen** [pionxzh/Pornhub.js#110]
As the title says, I'm confused about why only models has the `mostRecentVideos` property and pornstars do not? :)

**Comment by pionxzh** [comment]
I have added that property to `.pornstar()`.

https://github.com/pionxzh/Pornhub.js/pull/75#discussion_r1273495701
This is the discussion when we add `mostRecentVideos` to the model page... I'm 100% sure if the reason is still valid now. But it seems to work fine. So let's gooo~
