### ISSUE TITLE
`<pornstar>.mostRecentVideos` returns empty array if no recent UPLOADED videos, but with recent TAGGED videos.

### ISSUE THREAD

**Issue by iced-queen** [pionxzh/Pornhub.js#112]
With pornstars, if they don't have any recent UPLOADED videos, the `mostRecentVideos` property returns an empty array.
For example if trying with https://www.pornhub.com/pornstar/mia-khalifa who obviously has videos, it returns an empty array because she doesn't have any UPLOADED videos, only tagged. The array returns as expected if they DO have recent UPLOADED video(s).

I don't know if this happens to models as well as I haven't been able to find a model with no recent UPLOADED videos but some recent TAGGED videos, since models I think always just uploads their content themselves.

**Comment by pionxzh** [comment]
hmm I think we might need to add `taggedVideos`. Let me investigate more.

**Comment by pionxzh** [comment]
I have added support for `uploadedVideos` in `.pornstar`. Let me know if you see any incorrect behavior.

I realized that the current implementation is not 100% accurate, it might put videos in the wrong array in some layout. The name "mostRecentVideos" is a bad idea.
