### ISSUE TITLE
how to convert Embed Url Pornhub to hls m3u8 play

### ISSUE THREAD

**Issue by bobwatcherx** [pionxzh/Pornhub.js#113]
I found another pornhub library without using VPN. 
this repo
https://github.com/sinkaroid/lustpress

and API url
https://lust.scathach.id/pornhub/random

but in this library I can't embed because the Porhub domain is blocked. but in your package. I can get Hls m3u8 player . 

example
`https:\\/\\/ev-h.phncdn.com\\/hls\\/videos\\/202306\\/26\\/434287911\\/,1080P_4000K,720P_4000K,480P_2000K,240P_1000K,_434287911.mp4.urlset\\/master.m3u8?validfrom=1714184577&validto=1714191777&ipa=180.243.177.53&hdl=-1&hash=ahUVMN7fa4Um0Elt%2FSduOHkYcLg%3D`

and it is not blocked in my country. Tell me can you make the pornhub Embed URL into m3u8 hls ? thx

**Comment by pionxzh** [comment]
You can use `lustpress` to get the video id and call Pornhub.js again to get the m3u8 url.
