### ISSUE TITLE
All videos are returning 404

### ISSUE THREAD

**Issue by cocapeanut** [pionxzh/Pornhub.js#119]
I have quite a lot experience with m3u8 video players. 

This is one sample of the mediaDefinitions

```
{
      defaultQuality: false,
      format: 'hls',
      videoUrl: 'https:\\/\\/ev-h.phncdn.com\\/hls\\/videos\\/202402\\/29\\/448865721\\/1080P_4000K_448865721.mp4\\/master.m3u8?validfrom=1722125821&validto=1722133021&ipa=157.52.253.244&hdl=-1&hash=vGqgR4ptHxTIEYJo78neNXy3aIQ%3D',
      quality: 1080,
      remote: false
    },
```
    
     Usually to be able to play this you need to add proxy in front of it like so
   
`https:\example-proxy.com?url=https:\\/\\/ev-h.phncdn.com\\/hls\\/videos\\/202402\\/29\\/448865721\\/1080P_4000K_448865721.mp4\\/master.m3u8?validfrom=1722125821&validto=1722133021&ipa=157.52.253.244&hdl=-1&hash=vGqgR4ptHxTIEYJo78neNXy3aIQ%3D`
    The cors error is gone but network error is saying 404. they cant be all returning 404 right? that means either the video is deleted or the m3u8 url is wrong. even vlc player which doest require cors cant play the m3u8 url
     
     
     you can try it yourself
     https://m3u8play.dev

**Comment by pionxzh** [comment]
This is because the `videoUrl` are not unescaped. You can use `url.replace(/\\/g, '')` to fix the URL. I will publish a new version with the fix.

**Comment by cocapeanut** [comment]
![image](https://github.com/user-attachments/assets/2f2bf9ee-2565-4c6d-9f5c-a76cf116fde7)

even after **url.replace(/\\/g, '') **

 you can try it yourself
 https://m3u8play.dev

**Comment by pionxzh** [comment]
Let me try the player you provided later. But it does work for me with PotPlayer.

**Comment by pionxzh** [comment]
That is because of the CORS issue. Try some local m3u8 player.
