### ISSUE TITLE
v 1.12.2 not yet available in npm

### ISSUE THREAD

**Issue by cocapeanut** [pionxzh/Pornhub.js#122]
➜ `npm install pornhub.js@1.12.2 --save`
npm error code ETARGET
npm error notarget No matching version found for pornhub.js@1.12.2.
npm error notarget In most cases you or one of your dependencies are requesting
npm error notarget a package version that doesn't exist.

when I force it
➜ `npm install github:pionxzh/Pornhub.js#pornhub.js-v1.12.2`
the install works but the package is empty

![image](https://github.com/user-attachments/assets/b471d8d9-b4d2-446c-b45e-daea17a0967f)

https://www.npmjs.com/package/pornhub.js its still 1.12.1 here

**Comment by pionxzh** [comment]
See https://github.com/pionxzh/Pornhub.js/issues/120#issuecomment-2278417997
It's here https://www.npmjs.com/package/pornhub.js/v/1.12.2

Sorry for the inconvenience. 🙏
