### ISSUE TITLE
Video provider doesnt work

### ISSUE THREAD

**Issue by chocobearxo** [pionxzh/Pornhub.js#25]
For some reason, the video provider is always empty and doesnt provide either username or url

**Comment by pionxzh** [comment]
They changed the dom structure.
I will try to fix it this weekend.

**Comment by pionxzh** [comment]
I just released 0.30 to fix everything but the video, it's quite weird on my side...
I need to take more time to find the root cause

**Comment by pionxzh** [comment]
Actually, this one has been fixed in `0.30.0`. What I mentioned before has been moved to https://github.com/pionxzh/Pornhub.js/issues/27 .
Let me know if you still encountered this problem.
