### ISSUE TITLE
Add support for searching PH models

### ISSUE THREAD

**Issue by chocobearxo** [pionxzh/Pornhub.js#26]
Is it possible to do so it can also search for PH models and not only pornstars? Because Sometimes when searching for pornstars who turns how to be a model, it gets someone completely different

**Comment by pionxzh** [comment]
I'm not sure is the "models" idea exist back to the time I create this library, but yes I think it's a good idea to add this!

**Comment by pionxzh** [comment]
Sorry for being so late.
I just check the website and try to find "models", could you provide any examples for me to check? 🙏
I couldn't find any 😢

**Comment by ShadowBr0ther** [comment]
@pionxzh Hello! Did you had any success adding this feature of finding the right api call for it?

**Comment by pionxzh** [comment]
@ShadowBr0ther @chocobearxo 
Currently, pornhub doesn't provide any API/page to "**search**" for models.
I can integrate the auto-complete API to get a list of the model's "**name**", I'm not sure if this is good enough to meet your requirements.

**Comment by ShadowBr0ther** [comment]
Oh okay. 
Yeah that would be nice to 😊
Do you have a API documentation from pornhub? I can't find anything out there

**Comment by pionxzh** [comment]
> Oh okay. 
> Yeah that would be nice to 😊
> Do you have a API documentation from pornhub? I can't find anything out there

No, I just realized currently my repo is the best API document for pornhub. Lol
I already forgot how I get the API spec and document when I created this library. 😥

**Comment by ShadowBr0ther** [comment]
Yeah it totally is the best documentation out there. Shame on Pornhub

**Comment by pionxzh** [comment]
@ShadowBr0ther and @chocobearxo 
could you guys share more about what you need?

For now, these are the things that I can implement:
1. Fuzzy **searching** for models
=> `luna` ->
```js
// name only
// limit: 10 results
[
    "Luna Okko",
    "Luna Roulette",
    "lunaalessandra",
    ...
]
```
2. API for `name` -> `model page`?
=> `luna okko` -> https://cn.pornhub.com/model/luna-okko
3. API for `name` -> `model information(scraping)`?
=> `luna okko` -> 
```js
{
    name: "",
    gender: "female",
    otherProperties: true,
}
```

If we do `1` first and do `3` on each of the results, I'm worrying about triggering the soft ban. 
so maybe I can provide all of these APIs, and you guys can combine them on your own?

**Comment by ShadowBr0ther** [comment]
Sounds good!
How did you find those apis and ways to get the data, besides scraping?

**Comment by pionxzh** [comment]
> Sounds good! How did you find those apis and ways to get the data, besides scraping?

I alr lost the magic to get the API spec 🤣
now it's more like finding things in network panel

**Comment by pionxzh** [comment]
@ShadowBr0ther FYI, I'm working on [V2](https://github.com/pionxzh/Pornhub.js/tree/next) which will be migrated to fully Typescript.
I just implemented the `AutoComplete` and **searchModel** API.
Just want to double-check with you, do you still need this?
> API for name -> model information(scraping)?

And I think the new version should be a better document for you^^

**Comment by ShadowBr0ther** [comment]
Yeah would be very nice if you could implement it 😄

Awesome!

⁣BlueMail for Android herunterladen ​

Am 18. Okt. 2022, 19:45, um 19:45, Pionxzh ***@***.***> schrieb:
***@***.*** FYI, I'm working on

**Comment by chocobearxo** [comment]
Just curious, what would we be able to search for in v2? :)

**Comment by pionxzh** [comment]
> Just curious, what would we be able to search for in v2? :)

What do you mean 🤣
It was `v0.3.0`, now `v1`

You can find all of the search types here
https://github.com/pionxzh/Pornhub.js/blob/master/doc/Search.md

If you need any unsupported new search type, please open a new feature request.

**Comment by chocobearxo** [comment]
You just said "I'm working on V2"? XD

**Comment by pionxzh** [comment]
I thought it was V1, so the next one should be... V2. 😆

**Comment by chocobearxo** [comment]
Bruh so what would we be able to search for in the next version? 😆

**Comment by pionxzh** [comment]
I will integrate google so that users can search for anything they want 🤣

**Comment by chocobearxo** [comment]
I only need it for p*rn 😂
