### ISSUE TITLE
Video been redirected to a corn video

### ISSUE THREAD

**Issue by pionxzh** [pionxzh/Pornhub.js#27]
No matter what video you are trying to download, it will be redirected to the [same corn video](https://cn.pornhub.com/view_video.php?viewkey=ph56f0404ce4d73)...
> Tons of hard cobs getting grabbed

it might be caused by some anti-crawler things on Pornhub, you will need to use a VPN to bypass it.
At first, I think they flagged my IP because of the E2E testing 🤣 
But it's totally fine for me to watch them on a normal browser so... IDK

Related: 
- https://www.reddit.com/r/Pornhub/comments/q7yml6/anyone_elses_video_redirecting_to_a_corn_vid/
- https://github.com/KurtBestor/Hitomi-Downloader/issues/5170

**Comment by Hyoros** [comment]
That reddit link
"This subreddit was banned due to being unmoderated."
every time

**Comment by pionxzh** [comment]
@Hyoros I would like to share my finding with you.

It looks like PH will redirect the user without proper cookies to the corn video.
So the solution I implemented is:
1. Application will hold a singleton request sender, handling the `Set-Cookie` header.
2. Application will call main page once on startup (to set the cookie).
3. Ta-Da, it's all good now.

Maybe I can do more research to see which cookie is the key (and skip the redundant call).
But ye, it works.

**Comment by Hyoros** [comment]
That is a sensible explanation and apply to my case. Thanks for the enlightment
