### ISSUE TITLE
is not working 

### ISSUE THREAD

**Issue by Salientekill** [pionxzh/Pornhub.js#32]
![Screenshot_20221102-162604_Acode](https://user-images.githubusercontent.com/107017350/199583688-71877cde-e0e4-423b-9cc2-f9222cdc33b6.jpg)
![Screenshot_20221102-162638_Termux](https://user-images.githubusercontent.com/107017350/199583854-21b9d187-6441-48f2-9d89-48d16af80f78.jpg)

**Comment by Salientekill** [comment]
not generating URL link

**Comment by pionxzh** [comment]
Please see #27
