### ISSUE TITLE
searchModel errors

### ISSUE THREAD

**Issue by chocobearxo** [pionxzh/Pornhub.js#35]
**How I'm using it:**
```js
let pornhubSearch = 'candy love' // just an example
await pornhub.searchModel(pornhubSearch) // btw this is line 172 in my code
```
**Error:**

![error](https://i.gyazo.com/3a05dbae68d8eb51a005fc100a4e98c7.png)

**Comment by pionxzh** [comment]
fixed in [v1.0.3](https://github.com/pionxzh/Pornhub.js/releases/tag/v1.0.3)

**Comment by chocobearxo** [comment]
Could you also do so the `model` function also returns the amount of videos the model has like it does with pornstars?

**Comment by pionxzh** [comment]
Do you mean unify the return format of `searchModel` to be like this?
```json5
{
  paging: { current: 1, maxPage: 1, isEnd: true},
  counting: { from: 1, to: 22, total: 93 }
  data: [...the original result]
```

**Comment by pionxzh** [comment]
For the banner, please open a feature request issue. Thanks!

**Comment by chocobearxo** [comment]
No, I mean from
```js
let info = await pornhub.model(result.url) //result.url is the url of a model
console.log(info)
```
![pic](https://i.gyazo.com/cc01504dd66d3315fcdda05f1bebf34c.png)

**Comment by pionxzh** [comment]
sorry, could you specify the missing property name you want?
> the amount of videos the model has like it does with pstars

Pornstar doesn't have this feature too 🤔

**Comment by chocobearxo** [comment]
It has `videoNum`? 😅

**Comment by pionxzh** [comment]
oh lol, I just checked the code, and there is an unused interface `ModelSearchResult` which contains `videoNum` 🤣 

This `videoNum` is not possible for `searchModel` because of the limitation of the source API

**Comment by chocobearxo** [comment]
How about for `model` that already returns a lot more than `searchModel`? 
I'm already using both, `searchModel` to get the name and url and `model` for everything else, so couldn't you add it to `model` instead then? :D

**Comment by pionxzh** [comment]
Yes, that would be a good idea.
Feature request go go go. 😄

**Comment by chocobearxo** [comment]
Do I need to create a new feature request issue for this or is it fine I'm just suggesting it here? :D

**Comment by pionxzh** [comment]
It would be easier to manage with a new feature request.
You can update the existing feature request too.

**Comment by chocobearxo** [comment]
But I don't know if it would make more sense if the `videoNum` from `searchPornstar` was moved to `pornstar` aswell, so they're kinda in the same place as `videoNum` would be in `model`? Just a thought :D

**Comment by pionxzh** [comment]
I don't have a plan to "move" `videoNum` :/
It's more like parsing additional data in `pornstar` and `model`.

Btw, why I named `videoNum` rather than `videoCount` ?? what was I thinking? 🤣

**Comment by chocobearxo** [comment]
Yeah `videoCount` would make more sense 😂 

And that looks fine I think :smile:

**Comment by chocobearxo** [comment]
When will you release the next version? 🙂

**Comment by chocobearxo** [comment]
Also I found another bug.
From this line:
```js
const provider = providerLink.length ? { username: providerLink.text(), url: getAttribute(providerLink, "href", "") } : null;
```
With some providers, it returns the `username` twice.
```js
  provider: {
    username: 'Antonio MallorcaAntonio Mallorca',
    url: '/pornstar/antonio-mallorca'
  },
  ```
  On PH it doesn't repeat, but it does here.
  With E.G Bangbros, it doesn't repeat.
  Just wanted to let you know.
