### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by Salientekill** [pionxzh/Pornhub.js#39]
![Screenshot_20221207-211425_Termux](https://user-images.githubusercontent.com/107017350/206325131-e6ea4aa6-e3c0-44e4-9037-ef00733d822d.jpg)
![Screenshot_20221207-211514_Acode](https://user-images.githubusercontent.com/107017350/206325138-bec49e4b-6756-41ae-a0dd-ee2e998175c1.jpg)

**Comment by pionxzh** [comment]
This video has been deleted. Expected bahavior.
