### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by notsapinho** [pionxzh/Pornhub.js#4]
When i try to get a video info it returns: Unexpected end of JSON input

**Comment by pionxzh** [comment]
I will release new version which will include the fix

**Comment by pionxzh** [comment]
@notsapinho v0.2.3 should have fixed this issue
Let me know if you still encountered this problem.

**Comment by Mallybuz** [comment]
Still having this issue for some videos on 1.12.2

**Comment by pionxzh** [comment]
@Mallybuz Can you provide a reproduction?
