### ISSUE TITLE
TypeError: urlcat is not a function

### ISSUE THREAD

**Issue by WickedScissors** [pionxzh/Pornhub.js#40]
Getting the following error
```
file:///C:/Users/user/phproj/node_modules/pornhub.js/dist/index.mjs:159
var WebmasterBaseUrl = urlcat(BASE_URL, "/webmasters");
                       ^

TypeError: urlcat is not a function
    at file:///C:/Users/user/phproj/node_modules/pornhub.js/dist/index.mjs:159:24
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

Node.js v19.2.0
```
Using the following code
```js
import { PornHub } from 'pornhub.js'
const pornhub = new PornHub();

(async () => {
        const result = pornhub.searchVideo('small');
        console.log(result.length);
})()
```

Currently using release 1.1.0 of pornhub.js. Any clue what the issue could be?

**Comment by pionxzh** [comment]
Should be ESM related issues. Maybe urlcat is a esm only package?
Can you try this with cjs mode?

**Comment by pionxzh** [comment]
Can you try 1.0.3? maybe tsup screw up something?

**Comment by pionxzh** [comment]
I am currently on vacation. It would be great if you or someone can work on this issue. 🙏 I will be available to review PRs. Sorry for the inconvenience.

**Comment by pionxzh** [comment]
Interesting...
https://github.com/balazsbotond/urlcat/issues/171
