### ISSUE TITLE
Get PH models by ranking

### ISSUE THREAD

**Issue by ShadowBr0ther** [pionxzh/Pornhub.js#44]
Hello, 
would it be possible that you could implement a function where I can get all models sorted by their ranking?

**Comment by pionxzh** [comment]
From what PH already provided on their page, it would be impossible to implement such a feature.
You can only navigate to the "next" model one by one. They don't have a list 😞

**Comment by ShadowBr0ther** [comment]
Actually they have the verified amateur overview, where you can sort them by their ranking, so you can scrape those pages and get the data. Dirty but works. ^^

**Comment by pionxzh** [comment]
@ShadowBr0ther Could you show me the link?

**Comment by ShadowBr0ther** [comment]
Here: 
https://de.pornhub.com/pornstars?performerType=amateur

**Comment by pionxzh** [comment]
> Here: 
> https://de.pornhub.com/pornstars?performerType=amateur

Great. I also found it links to another top 800 list.

**Comment by pionxzh** [comment]
Check the usage here.
[/doc/Search.md#pornstarlist](https://github.com/pionxzh/Pornhub.js/blob/master/doc/Search.md#pornstarlist)

**Comment by ShadowBr0ther** [comment]
Very nice! Good work! 😋
However do you also support the gay pornstars and gay models since they are isolated from the normal list?

The url would be like this:
https://de.pornhub.com/gay/pornstars?performerType=amateur

**Comment by pionxzh** [comment]
ah I didn't know there is a gay one. I will add support for it later.

**Comment by ShadowBr0ther** [comment]
Yeah, every functionality is kind of separated and mirrored under the /gay/ subdomain. Pretty weird and dirty solution from Pornhub in my opinion.

**Comment by pionxzh** [comment]
Fixed in [v1.3.1](https://github.com/pionxzh/Pornhub.js/releases/tag/v1.3.1)

I might need to find some time to check and add support for gay on most of features 🤔

**Comment by pionxzh** [comment]
@ShadowBr0ther  I have implemented the `/gay` sub-domain for all supported functionality. See [v1.5.0](https://github.com/pionxzh/Pornhub.js/releases/tag/v1.5.0)
