### ISSUE TITLE
Illegal searches

### ISSUE THREAD

**Issue by chocobearxo** [pionxzh/Pornhub.js#45]
Hey,

I am using this library on a verified Discord bot, where I've seen it sadly being used in malcious ways like searching for illegal p*rn.
Currently when this occurs the bot just errors. But here's a suggestion:
In case someone searches for something "illegal" like CP or R*pe or other kinds of illegal p*rn, can you make it instead of trying to return results and information about those results (which will error in those cases), make it return something related to this issue.

I know pornhub returns with a special screen in case of illegal searches shown in the screenshots below:
![image](https://user-images.githubusercontent.com/108760175/220809895-49895ec1-7261-4750-98f4-39c9b3045d24.png)
![image](https://user-images.githubusercontent.com/108760175/220809861-ccbf8854-a32f-4889-b99d-9f8491dcdc3f.png)

I think it'd be a good idea to make this library return with at least something in case of illegal searches. E.g. it could return with a simple boolean like `illegal_search: true/false` and if it's true then also return the reason so the developer can write in their own message for those reasons.

If you need any further explaination, let me know. :)
(Apologies if this is really messy written as I wrote it at 3am)

**Comment by pionxzh** [comment]
Thanks for the suggestion. Tbh I have never seen these warning screens before.

I'm thinking about implementing this by throwing CustomError like `IllegalSearchError` with a reason on it.

**Comment by chocobearxo** [comment]
It's positive you haven't 😅
I've seen people using my bot to search for malicious stuff where it errored. And even though I'm not surprised it did, I still had to figure out WHY it errored and realised this is the reason for it.

I think that's an awesome and very useful idea that you should definitely implement!
It doesn't have to be a long description, but just a keyword for the developers to check and write in their own description if wanted.

**Comment by chocobearxo** [comment]
When about do you think you can make this? 😄

**Comment by pionxzh** [comment]
By the end of this week? If you are lucky then maybe tonight 🤣

**Comment by chocobearxo** [comment]
Sounds great - Hope you find the time asap 😄

**Comment by chocobearxo** [comment]
I'd assume the tricky part for this new update would be getting a list of all illegal types of searches to give those warnings a `reason`, so I just tried to find some sort of list to give you that would speed up the process and make it easier for you, but had no luck with that.
All I know of to be illegal to search for on Pornhub would be CP, gore, r*pe and animal abuse (obviously) but surely there's more than that.

**Comment by pionxzh** [comment]
Example
```js
import { IllegalError } from 'pornhub.js'

(async () => {
    try {
        const result = await pornhub.searchVideo(keyword)
    } catch (err) {
        if (err instanceof IllegalError) {
            console.log('Illegal search detected')
            console.log(err.message) // Your search could be for illegal and abusive sexual material, where children have suffered harm.
        }
    }
})()
```

**Comment by chocobearxo** [comment]
Great to see you got it! 😄 

How can I get all the text that's below?
E.g. if it errors with "Your search could be for illegal and abusive sexual material, where children have suffered harm." I wanna get all the text in the paragraph below it that'd be "Do not cross the line from legal....".

Also, if one or more word(s) is a hyperlink, can you make it return as markdown like such: `[text](link)`?

**Comment by pionxzh** [comment]
> I wanna get all the text in the paragraph below it that'd be "Do not cross the line from legal....". 
> Also, if one or more word(s) is a hyperlink, can you make it return as markdown like such: `[text](link)`?

May I know what is the use case of this? You want to show this to end user?

**Comment by chocobearxo** [comment]
I want to show it to the end user yes. But since I don't know all the possible warnings, this could cause issues.
So I thought maybe you could have the text you have now as `reason` and the more descibed text beneath it as `message`?

**Comment by pionxzh** [comment]
> But since I don't know all the possible warnings
I mean you can do logging and aggregate all the error messages. Then you will have a list of errors, you can use this as a possible warning list. And periodically check untracked error logs.

It would be a little bit weird for this library to scrape the entire error message in markdown.
