### ISSUE TITLE
Get the most recent videos from a model page

### ISSUE THREAD

**Issue by ShadowBr0ther** [pionxzh/Pornhub.js#53]
Hey, since you crape the model page, wouldn't it be interesting to scrape the most recent video URLs and informations to?
Maybe you want to scrape https://pornhub.com/model/xy/videos since you can get all the information there as well but you are be able to scrape all videos existing. 
Would be very helpful!

**Comment by pionxzh** [comment]
Yes it should be able to be implemented. I will need some time to check. They have some different templates for this page.

**Comment by chocobearxo** [comment]
Hey, just wanna bump this suggestion in case you forgot as I would also love to see this feature 😄

**Comment by pionxzh** [comment]
Thanks for the reminder!

**Comment by pionxzh** [comment]
They wont be two additional objects; instead, you can pass order=most viewed / recent as an option to get the video list.

**Comment by j-talas** [comment]
Hi @pionxzh !

I created PR #75 for this enhancement. Could you please kindly review?

Best Regards,
j-talas

**Comment by pionxzh** [comment]
Sure, I will check later. Thanks!
