### ISSUE TITLE
Search is returning empty/false values

### ISSUE THREAD

**Issue by SiSchu** [pionxzh/Pornhub.js#55]
```JS
{
  data: [],
  paging: { current: NaN, maxPage: NaN, isEnd: true },
  counting: { from: 0, to: 0, total: 0 }
}

let title = "hentai"
const search = (await pornhub.searchVideo(title))
console.log(search)
```

**Comment by pionxzh** [comment]
It's working on my side. Can you visit this URL without a problem?
`https://www.pornhub.com/video/search?search=hentai`

**Comment by SiSchu** [comment]
I can open the website but if I request it with the code above then the result is still like what I wrote.

**Comment by chocobearxo** [comment]
Hey @SiSchu,
What returns if you log `search.data`?

**Comment by pionxzh** [comment]
How about other APIs like `.video('ph5ac81eabe203d')` and `.searchAlbum(keyword)`?
I suspect it might be a network or language related problem.

**Comment by pionxzh** [comment]
Closing this issue as we haven't received any further updates or reports on the issue. If you experience the problem again, feel free to reopen this issue and provide more details.
