### ISSUE TITLE
Suggestion for a new project

### ISSUE THREAD

**Issue by chocobearxo** [pionxzh/Pornhub.js#56]
I didn't really know where to request this, so I'll just submit an issue here xd.

Since you made Pornhub.js and that is really easy to use I wanted to ask if you could also make a library for **https://tiktits.com** where you'd be able to get a random video / search for a video and return a result the same way Pornhub.js returns results 😄

**Comment by pionxzh** [comment]
Sorry I don't have the plan to work on that.
