### ISSUE TITLE
yt-dlp

### ISSUE THREAD

**Issue by inventor2525** [pionxzh/Pornhub.js#57]
Just had to poke in an fyi for the lacking video download. I'm pretty sure [yt-dlp](https://github.com/yt-dlp/yt-dlp) can handle practically anything. :wink: 

AI video training soon much? :stuck_out_tongue_winking_eye:

**Comment by pionxzh** [comment]
The solution I implemented years ago is no longer working. I have also checked the implementation in `yt-dlp`, but just kind of lazy to port all of them back to this library. 😅

**Comment by inventor2525** [comment]
IPC or... even TCP with side app.

**Comment by inventor2525** [comment]
It was just an FYI when I saw thing. Don't worry about it too much.

If someone had the compute (I don't atm) and wanted to train a video generator, they'd want to easily be able to download many videos with some rating or meta data content filter... but they could fairly easily at least use your thing to get the meta data and then download the video separately.

**Comment by pionxzh** [comment]
I see haha. Thanks for that.

For data scraping, it should be pretty easy to use this library to collect a list of videos and their metadata. Then write the list of video URLs to a file and call yt-dlp to download them all.

Maybe I should update the README to totally remove the part about video downloading with an explanation.

**Comment by pionxzh** [comment]
updated in https://github.com/pionxzh/Pornhub.js/commit/304f22109c4e405d07d78671a093de5b9690f6bd
