### ISSUE TITLE
SearchPeriod should be part of VideoSearchOptions

### ISSUE THREAD

**Issue by infiniporn** [pionxzh/Pornhub.js#59]
Wonderful package my friend. Would love it you could set SearchPeriod in VideoSearchOptions.

**Comment by pionxzh** [comment]
Could you share an example of it in the full search URL? I didn't find anywhere that allows for that use case.

**Comment by infiniporn** [comment]
Sure, ex: https://www.pornhub.com/video/search?search=milf&o=mv&t=w

The setting only shows up in the UI if you order by most viewed or top rated I think.

**Comment by pionxzh** [comment]
I see. Thanks.
