### ISSUE TITLE
Appears to be a git repo or submodule.

### ISSUE THREAD

**Issue by ratdeveloper** [pionxzh/Pornhub.js#6]
Error:
npm ERR! code EISGIT
npm ERR! path C:\Users\RDev\Desktop\dev\dpb\node_modules\pornhub.js
npm ERR! git C:\Users\RDev\Desktop\dev\dpb\node_modules\pornhub.js: Appears to be a git repo or submodule.
npm ERR! git     C:\Users\RDev\Desktop\dev\dpb\node_modules\pornhub.js
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

and i cant install any npm modules

**Comment by sayuribotbr** [comment]
Delete the .git folder inside node_modules/pornhub.js folder.

**Comment by ratdeveloper** [comment]
Thx
