### ISSUE TITLE
Get Random Video Function

### ISSUE THREAD

**Issue by chocobearxo** [pionxzh/Pornhub.js#62]
Hey there,
I love this library (as you can probably tell since this isn't my first suggestion xD), and I think it'd be a cool-to-have feature if there was a `randomVideo` function that would _obviously_ return a random video. 😄 Not just one of the first few "Most Viewed" ones as an example, but completely random.
This could also work with Pstars and Models (`randomPornstar` & `randomModel`).
These functions could also take tags as well (optional) that'd return a random video/pstar/model with these tags, but if no tags are provided, just a completely random video/pstar/model.

I don't even know if this is possible and/or if you wanna make it, but worth a try. 😊

**Comment by chocobearxo** [comment]
With a quick google search, I found a URL looking like this: http://www.pornhub.com/random
When I clicked on it, it redirected me onto a completely random video (I think), so I do actually think it is possible :))

Although, I do not know if this allow configs.

**Comment by pionxzh** [comment]
Good. Then we can have a `randomVideo()` 😄

**Comment by chocobearxo** [comment]
Great! I'm trying to figure out if it provides optional tags & if there's an endpoint like this for Pstars/Models as well, so they can all be in the same release if they exist. 😄

**Comment by chocobearxo** [comment]
Also I have a quick question. Does the library support the endpoints "/recommended" and "/video?o=ht" (hottest world wide)?

**Comment by pionxzh** [comment]
`/recommended` is not being supported as it's a personalized page, and I didn't find any useful use case for this page.
`/video?o=?` is not being supported, but I think this is a valid use case, feel free to open another feature request!

**Comment by chocobearxo** [comment]
Do you have an (approx) ETA on the next release which contains the current "[issues](https://github.com/pionxzh/Pornhub.js/issues)"/suggestions?
