### ISSUE TITLE
Support the endpoint "/video?o=?"

### ISSUE THREAD

**Issue by chocobearxo** [pionxzh/Pornhub.js#63]
This could e.g be used to find the hottest videos.

`https://www.pornhub.com/video?o=ht` finds the hottest videos world wide.
You can also get it country based. For example, you can use the endpoint `/video?o=ht&cc=dk` which finds the hottest videos in Denmark. I do not know all the countries, but then I'd assume "cc=uk" is the hottest videos in the United Kingdom" and "cc=us" in the United States and etc.

It can also be used to find:
- Most Viewed (o=mv) which also supports the country configs
- Top Rated (o=tr)
- Newest (o=cm)

Then I also think it'd be cool to support the `/recommended` endpoint. Even though this is personlized, I hope there'd be some sort of work-around for this.

**Comment by pionxzh** [comment]
implemented, but I forgot to provide the cc list, will be fixed in the next version

**Comment by pionxzh** [comment]
Done in [v1.5.0](https://github.com/pionxzh/Pornhub.js/releases/tag/v1.5.0)
