### ISSUE TITLE
Return an MP4 link and a Download link when getting a video

### ISSUE THREAD

**Issue by chocobearxo** [pionxzh/Pornhub.js#64]
I think it'd be useful if videos provided an MP4 link.
In my use case, it'd be better and easier for users of my Discord bot to watch these videos if they could be sent directly to Discord as a video file, instead of only sharing a link. Many of my bot's users have requested this. 🙂 

Likewise, I think it'd be cool to have a Download link as well.
In my use case again, I'd be able to make a button with a direct download link, which in my opinion would be really cool!

(3 suggestion in 4 hours, I doubt I can think of more today xD)

**Comment by pionxzh** [comment]
Please check the statement on README
> Please note that video downloading is no longer supported. We are unable to provide a download link due to the changes made by PornHub. However, you can still download videos using alternative tools such as [yt-dlp](https://github.com/yt-dlp/yt-dlp).

They no longer provide a simple `.mp4` link for you to download. You can only get a m3u8 and use it to download the whole video.
