### ISSUE TITLE
Age confirmation required

### ISSUE THREAD

**Issue by dmitrypisanko** [pionxzh/Pornhub.js#67]
Hi. Lately Pornhub added age confirmation and search now is not working. To fix it just add this 3 lines to buildRequest method

```
if (!headers.Cookie) {
        headers['Cookie'] = 'accessAgeDisclaimerPH=1; cookiesBannerSeen=1; atatusScript=hide; ';
}
```

**Comment by chocobearxo** [comment]
Don't know if it was intentional or not, but you wrote `atatusScript=hide`. Did you mean `statusScript=hide`?

**Comment by pionxzh** [comment]
I think he's right. It's `atatusScript`.
![image](https://github.com/pionxzh/Pornhub.js/assets/9910706/92c39912-2aa8-49bd-b3ee-48ffeb05b933)

**Comment by pionxzh** [comment]
But I'm not sure how to trigger that age confirmation on my side. Let me check later. And I also noticed there are some interesting cookies.
`hasVisited=1` `expiredEnterModalShown=1`

**Comment by dmitrypisanko** [comment]
Hi, important cookie is this one "accessAgeDisclaimerPH=1". I added others just in case. To trigger it you need to use VPN with european IP, in my case it was one from Finland.

> But I'm not sure how to trigger that age confirmation on my side. Let me check later. And I also noticed there are some interesting cookies. `hasVisited=1` `expiredEnterModalShown=1`

**Comment by pionxzh** [comment]
I have added the `accessAgeDisclaimerPH` cookie to the default cookie store.
