### ISSUE TITLE
Minor issue with recommendedVideos()

### ISSUE THREAD

**Issue by chocobearxo** [pionxzh/Pornhub.js#69]
Hey there,

When I get a random video from the `searchVideo()` function, it returns the `result.preview` perfectly fine. But I noticed that with `recommendedVideos()` when getting a random video, it returns the `result.preview` but in a way smaller size. This happens every time and looks *really ugly* in an embed.

![InkedInkedcc355ebd2379a3ffa0a9523d6f4ebe37](https://github.com/pionxzh/Pornhub.js/assets/108760175/3ad93147-1f71-4954-91d8-b9f5ec134219)

**Comment by pionxzh** [comment]
The video search page provides review with size: **320x180**
And the recommended videos provides preview with size: **258x145**

I think we have no way to _**fix**_ it. If you only want to pick one video from the recommended page, you can search the title again and match the video id as a workaround.

Another powerful solution is to crack the secret of Pornhub's CDN image path to generate previews with any size we want. But I have no idea.
