### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ratdeveloper** [pionxzh/Pornhub.js#7]
Error:
npm ERR! code EISGIT
npm ERR! path C:\Users\RDev\Desktop\dev\dpb\node_modules\pornhub.js
npm ERR! git C:\Users\RDev\Desktop\dev\dpb\node_modules\pornhub.js: Appears to be a git repo or submodule.
npm ERR! git     C:\Users\RDev\Desktop\dev\dpb\node_modules\pornhub.js
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

and i cant install any npm modules

**Comment by pionxzh** [comment]
maybe you can take a look on this https://github.com/react-navigation/react-native-safe-area-view/issues/73
let me know if anything I can help from my side.
