### ISSUE TITLE
recommendedVideos() started to have issues

### ISSUE THREAD

**Issue by chocobearxo** [pionxzh/Pornhub.js#71]
The `recommendedVideos()` function has started to return objects like this:
```js
{ data: [], paging: { current: NaN, maxPage: NaN, isEnd: true } }
```

This is happening both on `v1.5.0` and `v1.5.1`.

**Comment by pionxzh** [comment]
does a downgrade to 1.5.0 or lower fix the issue? Not sure what's the problem.

**Comment by chocobearxo** [comment]
Apologies for the late response, I've been in cottage.
1.5.0 has the issue, it was introduced in 1.5.0 so I can't check the lower ones. 😄

**Comment by pionxzh** [comment]
let's discuss this in #73.
