### ISSUE TITLE
`randomVideo()` returns false information

### ISSUE THREAD

**Issue by chocobearxo** [pionxzh/Pornhub.js#84]
![img](https://i.gyazo.com/0f700b236f8aaa6b3929e204cd6f58f9.png)
![img](https://i.gyazo.com/7ca8a051868cd1fa136d56404f4858c5.png)

It's the same video by the way, since the `url` directed me to the first screenshot.

**Comment by pionxzh** [comment]
Duplicate of #68

**Comment by pionxzh** [comment]
I will try test this with an EU VPN
